/*
  generated by https://github.com/uladkasach/sql-schema-generator @v0.17.1
*/
CREATE FUNCTION `upsert_image`(
  in_url varchar(190),
  in_caption varchar(190),
  in_credit varchar(190),
  in_alt_text varchar(190)
) RETURNS bigint(20)
BEGIN
  -- declarations
  DECLARE v_static_id BIGINT;
  DECLARE v_created_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6); -- define a common created_at timestamp to use

  -- find or create the static entity
  SET v_static_id = (
    SELECT id
    FROM image
    WHERE 1=1
      AND (url = BINARY in_url)
      AND (caption = BINARY in_caption OR (caption IS null AND in_caption IS null))
      AND (credit = BINARY in_credit OR (credit IS null AND in_credit IS null))
      AND (alt_text = BINARY in_alt_text OR (alt_text IS null AND in_alt_text IS null))
  );
  IF (v_static_id IS NULL) THEN -- if entity could not be found originally, create the static entity
    INSERT INTO image
      (uuid, created_at, url, caption, credit, alt_text)
      VALUES
      (uuid(), v_created_at, in_url, in_caption, in_credit, in_alt_text);
    SET v_static_id = (
      SELECT last_insert_id()
    );
  END IF;

  -- return the static entity id
  return v_static_id;
END
