ignores:
  - depcheck
  - declapract
  - declapract-typescript-ehmpathy
  - '@commitlint/config-conventional'
  - husky
  - '@oclif/plugin-help'
  - oclif
  - '@types/yesql'
  - "@src/*"
  - "@src/.*"
  - rhachet
  - rhachet-brains-anthropic
  - rhachet-brains-xai
  - rhachet-roles-bhrain
  - rhachet-roles-bhuild
  - rhachet-roles-ehmpathy
  - rhachet-roles-rhachet
  - "@tsconfig/node20"
  - "@tsconfig/strictest"
  - "@biomejs/biome"
  - esbuild-register
  - "@swc/core"
  - "@swc/jest"
  - tsx
  - tsc-alias
  - yalc
