name: publish

on:
  push:
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} # per [workflow] x [branch, tag]
  cancel-in-progress: true #  cancel workflows for non-latest commits

jobs:
  test:
    uses: ./.github/workflows/.test.yml

  publish:
    uses: ./.github/workflows/.publish-npm.yml
    needs: [test]
    secrets:
      npm-auth-token: ${{ secrets.NPM_TOKEN }}
